/*
 * File: app/store/Customers.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Funzl.store.Customers', {
    extend: 'Ext.data.Store',
    alias: 'store.customers',

    requires: [
        'Funzl.model.Customer',
        'Ext.data.proxy.Rest'
    ],

    config: {
        autoLoad: true,
        autoSync: false,
        clearOnPageLoad: false,
        model: 'Funzl.model.Customer',
        remoteFilter: true,
        remoteSort: true,
        storeId: 'Customers',
        proxy: {
            type: 'rest',
            url: 'http://funzl-services.appspot.com/data/Customer'
        },
        sorters: {
            property: 'name'
        }
    }
});