/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    disableCaching: false,
    enabled: true
});

Ext.application({
    models: [
        'Feed',
        'MenuItem',
        'Address',
        'Contact',
        'Product',
        'ProductCategory'
    ],
    stores: [
        'Customers',
        'MenuList',
        'CustomerMenuList',
        'Products',
        'ProductCategories'
    ],

    name: 'Funzl',
    
    //The controllers' launch functions are called in the order they are declared here.
    //The launch functions are called before the init functions, and are used to initialize
    //the first views that appear in the application.
    controllers: [
        'MenuNavController',
        'MenuListController',
        'CustomerMenuListController',
        'DetailNavController',
        'Main',
        'CustomerTabPanelController',
        'CustomerListController',
        'CustomerListMapController',
        'CustomerDetailsController',
        'EditCustomerDetailsController',
        'ProductCategoryListController',
        'ProductListController',
        'ProductDetailsController'
    ],


    //this is called before the controllers' launch functions
    launch: function() {

    }

});
